# @package _global_
defaults:
  - override /loss: semantic_loss

dataset:
  output_structure:
    target: semantic_mask
  supercategories_only: True

model:
  encoder_depth: 5
  skip_connections: [True, True, True, True, True]
  encoder_weights: "imagenet"
  state_dict:
    _target_: torch.load
    f: /workspaces/master_thesis/code/models/pretrained-vae.pt
  load_encoder: True
  load_mid_block: True
  load_decoder: False

optimizer:
  lr: 1e-5
scheduler:
  eta_min: 1e-3

batch_size: 32
input_shape: [128, 128]
