# @package _global_
defaults:
  - override /loss: semantic_loss

dataset:
  output_structure:
    target: semantic_mask
  top_k_classes: 5

model:
  encoder_depth: 5
  skip_connections: [True, True, True, True, True]
  encoder_weights: "imagenet"

optimizer:
  lr: 1e-5

general:
  # batch_size: 64
  input_shape: [128, 128]