defaults:
  - default_dirs
  - dataset: coco
  - model: mobile_vae
  - scheduler: cosine_annealing
  - optimizer: adamax
  - loss: recon_loss
  - .@trainer: trainer
  - _self_

num_steps: 20_000
input_shape: [128, 128]
class_weights: null
batch_size: 64