defaults:
  - default_dirs
  - dataset: coco
  - model: mobile_vae
  - scheduler: cosine_annealing
  - optimizer: adamax
  - loss: recon_loss
  - .@trainer: trainer

general:
  batch_size: 64
  num_steps: 100_000
  input_shape: [256, 256]
