wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712662386.012019
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 63
      - 71
      - 74
      - 83
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 63
      - 71
      - 74
      - 83
      3:
      - 23
      4: 3.10.12
      5: 0.16.2
      6: 4.37.2
      8:
      - 5
      13: linux-x86_64
