# @package hydra.sweeper
_target_: hydra_plugins.hydra_ax_sweeper.ax_sweeper.AxSweeper
max_batch_size: null
ax_config:
  max_trials: 10
  early_stop:
    minimize: true
    max_epochs_without_improvement: 10
    epsilon: 1.0e-05
  experiment:
    name: null
    objective_name: objective
    minimize: true
    parameter_constraints: null
    outcome_constraints: null
    status_quo: null
  client:
    verbose_logging: false
    random_seed: null
  is_noisy: true
  params:
    ++num_steps:
      type: fixed
      value: 10_000
    ++scheduler.gamma:
      type: range
      bounds: [0.8, 1.0]
      log_scale: true
    ++optimizer.lr:
      type: range
      bounds: [1e-7, 1e-3]
      log_scale: true
