# @package hydra.launcher
_target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
n_jobs: 1
backend: null
prefer: processes
require: null
verbose: 0
timeout: null
pre_dispatch: 1
batch_size: 1
temp_folder: null
max_nbytes: null
mmap_mode: r