# @package hydra.launcher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 1440 #(24 * 60)
cpus_per_task: 7
gpus_per_node: 1
tasks_per_node: 1
mem_gb: null
nodes: 1
name: thesis-dik-${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
partition: mcs.gpu.q
qos: null
comment: null
constraint: "gforce"
exclude: null
gres: null
cpus_per_gpu: null
gpus_per_task: null
mem_per_gpu: null
mem_per_cpu: 4G
account: null
signal_delay_s: 120
max_num_timeout: 0
additional_parameters:
  nice: 10000
  mail-user: "h.j.m.v.genuchten@student.tue.nl"
array_parallelism: 256
setup: null
srun_args: null
