# This workflow will install dependencies, create coverage tests and run Pytest Coverage Commentator
# For more information see: https://github.com/coroo/pytest-coverage-commentator
name: pytest-coverage-commentator
on:
  pull_request:
    branches:
      - main

defaults:
 run:
  working-directory: ./code

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      working-directory: ./code
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
        pytorch-version:
          [2.2.2]
    steps:
      # vvvv Taken from https://github.com/pytorch/ignite/blob/master/.github/workflows/pytorch-version-tests.yml vvvv
      - uses: actions/checkout@v4
      - name: Get year & week number
        id: get-date
        run: echo "date=$(/bin/date "+%Y-%U")" >> $GITHUB_OUTPUT
        shell: bash -l {0}
      - name: Get pip cache dir
        id: pip-cache
        run: |
          python3 -m pip install -U pip
          echo "pip_cache=$(python3 -m pip cache dir)" >> $GITHUB_OUTPUT
        shell: bash -l {0}
      - uses: actions/cache@v3
        with:
          path: |
            ~/conda_pkgs_dir
            ${{ steps.pip-cache.outputs.pip_cache }}
          key: ${{ steps.get-date.outputs.date }}-pytorch-${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-${{ hashFiles('requirements-dev.txt') }}
          restore-keys: |
            ${{ steps.get-date.outputs.date }}-pytorch-${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install pytorch=${{ matrix.pytorch-version }} torchvision cpuonly python=${{ matrix.python-version }} -c pytorch
          pip install -r requirements.txt -r requirements-dev.txt
      # ^^^^ Taken from https://github.com/pytorch/ignite/blob/master/.github/workflows/pytorch-version-tests.yml ^^^^

      - name: Lint with Ruff
        working-directory: ${{env.working-directory}}
        shell: bash -l {0}
        run: |
          ruff --output-format=github .
      - name: Pytest
        working-directory: ${{env.working-directory}}
        shell: bash -l {0}
        run: |
          pytest
