# This workflow will install dependencies, create coverage tests and run Pytest Coverage Commentator
# For more information see: https://github.com/coroo/pytest-coverage-commentator
name: pytest-coverage-commentator
on:
  pull_request:
    branches:
      - main

defaults:
 run:
  working-directory: ./code

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./code
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "pypy3.11"
        # cache: "pip"
        # cache-dependency-path: ${{env.working-directory}}/requirements.txt
    - name: Install dependencies
      working-directory: ${{env.working-directory}}
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision
        pip install -r requirements_d.txt
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
    - name: Lint with Ruff
      working-directory: ${{env.working-directory}}
      run: |
        pip install ruff
        ruff --output-format=github .
      continue-on-error: true
    - name: Pytest
      working-directory: ${{env.working-directory}}
      run: |
        python -m pytest
